import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flashcard Saas",
  description: "Generated by Bishneet Rekhi",

};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" sizes="any"></link>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
